config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'help' =>  'static_pages#help'
  get 'about' =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :api, { format: 'json' } do
    match '*path' => 'application#preflight', via: :options
    resources :users, only: [:index, :show, :create, :update, :destroy] do
      member do
        get :following, :followers
      end
    end
    post 'login' => 'authentication#create'
    delete 'logout' => 'authentication#destroy'
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    |  The 
    a[href="http://www.railstutorial.org/"]
      | Ruby on Rails Tutorial
    |  by 
    a[href="http://www.michaelhartl.com/"]
      | Michael Hartl
  nav
    ul
      li
        = link_to "About", about_path
      li
        = link_to "Contact", contact_path
      li
        a[href="http://news.railstutorial.org/"]
          | News

app/views/layouts/_header.html.slim
header
  .container
    nav.navbar.navbar-fixed-top.navbar-inverse
      = link_to "Orpheus", root_path, id: "logo"
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
            span.icon-bar
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav.navbar-right
            li
              = link_to "Home", root_path
            li
              = link_to "Help", help_path
            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
                | Menu 
                span.caret
              ul.dropdown-menu
                - if logged_in?
                  li
                    = link_to "Users", users_path
                  li
                    = link_to "Profile", current_user
                  li
                    = link_to "Settings", edit_user_path(current_user)
                  li.divider
                  li
                    = link_to "Log out", logout_path, method: "delete"
                - else
                  li
                    = link_to "Log in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    == render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      == yield
      == render 'layouts/footer'
      = debug(params) if Rails.env.development?